# Generated by Django 4.2.3 on 2023-08-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0002_rename_user_doc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('departments', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('doc_image', models.FileField(default='pro.jpg', upload_to='product/')),
                ('doc_desc', models.TextField(max_length=500)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_doctor.doc_user')),
            ],
        ),
    ]
