# Generated by Django 4.2.3 on 2023-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc_image',
            field=models.FileField(default='pro.jpg', upload_to='profile/'),
        ),
    ]
