# Generated by Django 4.2.3 on 2023-08-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doctor', '0004_alter_profile_doc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc_image',
            field=models.FileField(default='anonymous.jpg', upload_to='media/'),
        ),
    ]
