# Generated by Django 4.2.3 on 2023-07-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
