# Generated by Django 4.2.3 on 2023-07-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0002_rename_fname_user_name_remove_user_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpassword',
        ),
    ]
